language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - yarn global add firebase-tools
    
install:
  - (cd functions && yarn install)

script:
  - yarn prod

after_success:
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT
